import Carousel from "../Carousel";
import Image from "next/image";
import styled from "styled-components";
const SliderImage = styled(Image)`
align-self: center,
padding: 0rem,
maring: 0rem;
`;
const AdvCarousel = () => {
    return (
        <Carousel>
            <div className="carousel-slide">
                <span>
                    <SliderImage
                        src={"/images/adv/char_card_288.png"}
                        width={500}
                        height={550}
                        quality={100}
                        alt="adv"
                    />
                </span>
            </div>
            <div className="carousel-slide">
                <span>
                    <SliderImage src={"/images/adv/2.png"} width={500} height={550} quality={100} alt="adv" />
                </span>
            </div>
            <div className="carousel-slide">
                <span>
                    <SliderImage
                        src={"/images/adv/char_card_549.png"}
                        width={500}
                        height={550}
                        quality={100}
                        alt="adv"
                    />
                </span>
            </div>
            <div className="carousel-slide">
                <span>
                    <SliderImage src={"/images/adv/1.png"} width={500} height={550} quality={100} alt="adv" />
                </span>
            </div>
            <div className="carousel-slide">
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_520.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_293.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/traveller-forked-beard.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_290.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_280.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_252.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_227.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_217.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_190.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/chain-eyepatch.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_171.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_164.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_158.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_155.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/claw-staff-tooth-hat.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_144.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
            </div>
            <div className="carousel-slide">
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_142.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_139.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_138.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage src={"/images/adv/mace-wiz.png"} width={120} height={120} quality={100} alt="adv" />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_131.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_111.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_107.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage src={"/images/adv/noface-mace.png"} width={120} height={120} quality={100} alt="adv" />
                </span>
                <span>
                    <SliderImage src={"/images/adv/portrait_84.png"} width={120} height={120} quality={100} alt="adv" />
                </span>
                <span>
                    <SliderImage src={"/images/adv/portrait_72.png"} width={120} height={120} quality={100} alt="adv" />
                </span>
                <span>
                    <SliderImage src={"/images/adv/portrait_21.png"} width={120} height={120} quality={100} alt="adv" />
                </span>
                <span>
                    <SliderImage src={"/images/adv/portrait_1.png"} width={120} height={120} quality={100} alt="adv" />
                </span>
                <span>
                    <SliderImage src={"/images/adv/portrait_28.png"} width={120} height={120} quality={100} alt="adv" />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_221.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
                <span>
                    <SliderImage src={"/images/adv/portrait_15.png"} width={120} height={120} quality={100} alt="adv" />
                </span>
                <span>
                    <SliderImage
                        src={"/images/adv/portrait_309.png"}
                        width={120}
                        height={120}
                        quality={100}
                        alt="adv"
                    />
                </span>
            </div>
        </Carousel>
    );
};

export default AdvCarousel;
