import GlobalConst from "./globalConst";
import {SkillD} from "./globalTypes";

export const GlobalSkills: SkillD[] = [
    {
        id: 1,
        minLevel: 2,
        maxLevel: 4,
        name: "Hobgob's Strength",
        description: "Brawn + 2",
        modifiers: {
            brawn: 2,
        },
        minStats: {
            brawn: 10,
        },
        stackable: false,
    },
    {
        id: 2,
        minLevel: 2,
        maxLevel: 4,
        name: "Wasp's Speed",
        description: "Agility + 2",
        modifiers: {
            agility: 2,
        },
        minStats: {
            agility: 10,
        },
        stackable: false,
    },
    {
        id: 3,
        minLevel: 2,
        maxLevel: 4,
        name: "Brownie's Wit",
        description: "Guile + 2",
        modifiers: {
            guile: 2,
        },
        minStats: {
            guile: 10,
        },
        stackable: false,
    },
    {
        id: 4,
        minLevel: 2,
        maxLevel: 4,
        name: "Troll's Will",
        description: "Spirit + 2",
        modifiers: {
            spirit: 2,
        },
        minStats: {
            spirit: 10,
        },
        stackable: false,
    },
    {
        id: 5,
        minLevel: 2,
        maxLevel: 3,
        name: "Wisp's Aura",
        description: "Resistance to Arcane & Divine Damage",
        stackable: false,
        resistances: [GlobalConst.DAMAGE_TYPES.ARCANE, GlobalConst.DAMAGE_TYPES.DIVINE],
    },
    {
        id: 6,
        minLevel: 2,
        maxLevel: 3,
        name: "Skell's Protection",
        description: "Resistance to Necrotic & Poison Damage",
        stackable: false,
        resistances: [GlobalConst.DAMAGE_TYPES.NECROTIC, GlobalConst.DAMAGE_TYPES.POISON],
    },
    {
        id: 7,
        minLevel: 2,
        maxLevel: 5,
        name: "Wyrden's Grace",
        description: "5% Dodge Bonus",
        stackable: false,
        modifiers: {
            dodge: 5,
        },
    },
    {
        id: 8,
        minLevel: 2,
        maxLevel: 5,
        name: "Dwarv's Training",
        description: "7% Block Bonus",
        stackable: false,
        modifiers: {
            block: 7,
        },
    },
    {
        id: 9,
        minLevel: 2,
        maxLevel: 4,
        name: "Vodyanoi's Blessing",
        description: " +1 to all BAGS attributes",
        stackable: false,
        modifiers: {
            brawn: 1,
            agility: 1,
            guile: 1,
            spirit: 1,
        },
    },
    {
        id: 10,
        minLevel: 2,
        maxLevel: 4,
        name: "Deadknight's Riposte",
        description: "Melee: Automatically strike back with melee weapon after blocking.",
        stackable: false,
    },
    {
        id: 11,
        minLevel: 2,
        maxLevel: 5,
        name: "Shadow Elf's Sight",
        description: "+5% bonus to Crit Chance",
        stackable: false,
        modifiers: {
            crit: 5,
        },
    },
    {
        id: 12,
        minLevel: 2,
        maxLevel: 5,
        name: "Arkan's Axe-sense",
        description: "+10% chance to crit with axes",
        stackable: false,
        modifiers: {
            custom: 10,
        },
        minStats: {
            brawn: 12,
        },
    },
    {
        id: 13,
        minLevel: 2,
        maxLevel: 5,
        name: "Sword-sense of the Shadow Elf",
        description: "+20% chance to hit with swords",
        stackable: false,
        modifiers: {
            custom: 20,
        },
        minStats: {
            brawn: 12,
        },
    },
    {
        id: 14,
        minLevel: 2,
        maxLevel: 5,
        name: "Brownie's Dagger-sense",
        description: "+10% chance to crit with daggers",
        stackable: false,
        modifiers: {
            custom: 10,
        },
        minStats: {
            agility: 12,
        },
    },
    {
        id: 15,
        minLevel: 2,
        maxLevel: 5,
        name: "Spear-sense of the Vodyanoi",
        description: "+20% chance to hit with spears",
        modifiers: {
            custom: 20,
        },
        stackable: false,
        minStats: {
            brawn: 12,
        },
    },
    {
        id: 16,
        minLevel: 2,
        maxLevel: 5,
        name: "Staff Attunement",
        description: "Increased chance for on-hit effects to fire",
        stackable: false,
        modifiers: {
            custom: 20,
        },
        minStats: {
            spirit: 12,
        },
    },
    {
        id: 17,
        minLevel: 2,
        maxLevel: 5,
        name: "Dwarv Lord's Hammersense",
        description: "+15% to block when a hammer is equipped",
        stackable: false,
        modifiers: {
            custom: 15,
        },
        minStats: {
            brawn: 12,
        },
    },
    {
        id: 18,
        minLevel: 2,
        maxLevel: 5,
        name: "Wererat's Cunning",
        description: "+30% bonus to all trap avoiding & disarming.",
        stackable: false,
    },
    {
        id: 19,
        minLevel: 2,
        maxLevel: 5,
        name: "Gains Goblin's Discount",
        description: "+50% to steal chance at merchants",
        modifiers: {
            custom: 50,
        },
        stackable: false,
    },
    {
        id: 20,
        minLevel: 2,
        maxLevel: 5,
        name: "Gargoyle's Fists",
        description: "Unarmed attacks strike as a Rare weapon",
        stackable: false,
    },
    {
        id: 21,
        minLevel: 2,
        maxLevel: 5,
        name: "Shield of the Phalanx",
        description: "+15% block when using any shield",
        modifiers: {
            custom: 15,
        },
        stackable: false,
    },
    {
        id: 22,
        minLevel: 2,
        maxLevel: 5,
        name: "Dramock's Fortitude",
        description: "Additional +20 HP",
        modifiers: {
            custom: 20,
        },
        stackable: false,
    },
    {
        id: 23,
        minLevel: 2,
        maxLevel: 5,
        name: "Kobold's Evasion",
        description: "25% dodge bonus against ranged attacks",
        stackable: false,
    },
    {
        id: 24,
        minLevel: 2,
        maxLevel: 4,
        name: "Jel Cubes' Bile",
        description: "Resistance to Fire, Cold & Electrical Damage",
        stackable: false,
        resistances: [GlobalConst.DAMAGE_TYPES.FIRE, GlobalConst.DAMAGE_TYPES.COLD, GlobalConst.DAMAGE_TYPES.ELECTRIC],
    },
    {
        id: 25,
        minLevel: 3,
        maxLevel: 5,
        name: "Ditchwitch's Brew",
        description: "Potions have a 40% chance to not be consumed after use.",
        stackable: false,
        modifiers: {
            custom: 40,
        },
    },
    {
        id: 26,
        minLevel: 3,
        maxLevel: 5,
        name: "Nightfather's Spellbook",
        description: "Scrolls have a 40% chance to not be consumed after use.",
        stackable: false,
        modifiers: {
            custom: 40,
        },
    },
    {
        id: 27,
        minLevel: 3,
        maxLevel: 5,
        name: "Feywing's Magicks",
        description: "Increased effectiveness of all scrolls.",
        stackable: false,
        minStats: {
            spirit: 12,
        },
    },
    {
        id: 28,
        minLevel: 3,
        maxLevel: 5,
        name: "Archery Expert",
        description: "No penalty when attacking with bows at 1 range.",
        stackable: false,
        minStats: {
            agility: 12,
        },
    },
    {
        id: 29,
        minLevel: 3,
        maxLevel: 5,
        name: "Wand Expert",
        description: "No penalty when attacking with wands at 1 range.",
        stackable: false,
        minStats: {
            spirit: 12,
        },
    },
    {
        id: 30,
        minLevel: 3,
        maxLevel: 5,
        name: "Cockatrice Blood",
        description: "Immune to hold and stun effects",
        stackable: false,
    },
    {
        id: 31,
        minLevel: 3,
        maxLevel: 5,
        name: "Rat's Stash",
        description: "Grow hungry 10x slower, hardly need to eat",
        stackable: false,
    },
    {
        id: 32,
        minLevel: 3,
        maxLevel: 5,
        name: "Quex's Blessing",
        description: "+25% bonus to all healing effects",
        stackable: false,
        modifiers: {
            custom: 25,
        },
    },
    {
        id: 33,
        minLevel: 3,
        maxLevel: 5,
        name: "Gargoyle's Strike",
        description: "Unarmed attacks have a 10% chance to Stun",
        stackable: false,
        requiredSkill: 20,
        modifiers: {
            custom: 10,
        },
    },
    {
        id: 34,
        minLevel: 3,
        maxLevel: 5,
        name: "Bubble Eyes' Charm",
        description: "+20% Bonus on all non-trap story events.",
        stackable: false,
        modifiers: {
            custom: 20,
        },
    },
    {
        id: 35,
        minLevel: 3,
        maxLevel: 5,
        name: "Mirthcreant's Escape",
        description: "If at low HP after being hit, chance to teleport away to a random location",
        stackable: false,
        modifiers: {
            custom: 65,
        },
    },
    {
        id: 36,
        minLevel: 3,
        maxLevel: 5,
        name: "Arkan's Strength",
        description: "All weapons are considered one-handed",
        stackable: false,
    },
    // {
    //     id: 37,
    //     minLevel: 3,
    //     maxLevel: 5,
    //     name: "Manticore's Resiliance",
    //     description: "Immune to effects that reduce BAGS attributes",
    //     stackable: false,
    // },
    {
        id: 38,
        minLevel: 3,
        maxLevel: 5,
        name: "Snake's Blood",
        description: "Immune to Poison",
        immunities: [GlobalConst.DAMAGE_TYPES.POISON],
        stackable: false,
    },
    // {
    //     id: 39,
    //     minLevel: 3,
    //     maxLevel: 5,
    //     name: "Greiger's Visage",
    //     description: "All attacks have a 5% to inflict fear (dweller attempts to flee)",
    //     stackable: false,
    //     modifiers: {
    //         custom: 5,
    //     },
    // },
    {
        id: 40,
        minLevel: 4,
        maxLevel: 5,
        name: "Stachelig Hide",
        description: "Resistance to Blade & Pierce",
        stackable: false,
        resistances: [GlobalConst.DAMAGE_TYPES.BLADE, GlobalConst.DAMAGE_TYPES.PIERCE],
    },
    {
        id: 41,
        minLevel: 4,
        maxLevel: 5,
        name: "Fomoian Skin",
        description: "Immune to Bludgeon Damage",
        stackable: false,
        immunities: [GlobalConst.DAMAGE_TYPES.BLUDGEON],
    },
    {
        id: 42,
        minLevel: 4,
        maxLevel: 5,
        name: "Bananach's Blood",
        description: "Immune to Cold",
        stackable: false,
        immunities: [GlobalConst.DAMAGE_TYPES.COLD],
    },
    {
        id: 43,
        minLevel: 4,
        maxLevel: 5,
        name: "Paralisk's Blood",
        description: "Immune to Fire",
        stackable: false,
        immunities: [GlobalConst.DAMAGE_TYPES.FIRE],
    },
    // {
    //     id: 44,
    //     minLevel: 4,
    //     maxLevel: 5,
    //     name: "Gem Lizard's Scales",
    //     description: "Beam attacks reflect.",
    //     stackable: false,
    // },
    // {
    //     id: 45,
    //     minLevel: 4,
    //     maxLevel: 5,
    //     name: "Goblin's Vision",
    //     description: "All traps are revealed by default.",
    //     stackable: false,
    // },
    // {
    //     id: 46,
    //     minLevel: 4,
    //     maxLevel: 5,
    //     name: "Traveler's Steps",
    //     description:
    //         "Chance every step of increased move speed (2 steps before dwellers act, does not give extra attacks)",
    //     stackable: false,
    // },
    {
        id: 47,
        minLevel: 4,
        maxLevel: 5,
        name: "Collector's Cartography",
        description: "The dungeon map is revealed at the start of each run",
        stackable: false,
    },
    // {
    //     id: 48,
    //     minLevel: 4,
    //     maxLevel: 5,
    //     name: "Ghast's Touch",
    //     description: "All melee attacks have a +5% chance to stun",
    //     stackable: false,
    //     modifiers: {
    //         custom: 5,
    //     },
    // },
    // {
    //     id: 49,
    //     minLevel: 0,
    //     maxLevel: 5,
    //     name: "Death from Afar",
    //     description:
    //         "Ranged weapons do 2x damage, but *all* weapons have a severe to-hit penalty at close range (range = 1)",
    //     stackable: false,
    // },
    {
        id: 50,
        minLevel: 0,
        maxLevel: 5,
        name: "Gem Lizard's Scales",
        description: "You are immune to arcane and electric attacks, but can no longer use scrolls or potions",
        stackable: false,
        immunities: [GlobalConst.DAMAGE_TYPES.ARCANE, GlobalConst.DAMAGE_TYPES.ELECTRIC],
    },
    // {
    //     id: 51,
    //     minLevel: 0,
    //     maxLevel: 5,
    //     name: "Barefoot Assassin",
    //     description: "You are a master of stealth but cannot wear shoes",
    //     stackable: false,
    // },
    {
        id: 53,
        minLevel: 0,
        maxLevel: 5,
        name: "Zombie's Bile",
        description: "Start run at half health, but you are revived once on dying",
        stackable: false,
    },
    {
        id: 55,
        minLevel: 0,
        maxLevel: 5,
        name: "Berserker's Fury",
        description: "2x damage, -40% to-hit",
        stackable: false,
        modifiers: {
            to_hit: -40,
            damage_mult: 100, //this is a percentage so 2x = 100
        },
    },
    {
        id: 56,
        minLevel: 0,
        maxLevel: 5,
        name: "Grieger's Reach",
        description: "Melee weapons have range 2",
        stackable: false,
    },
    {
        id: 57,
        minLevel: 2,
        maxLevel: 5,
        name: "Kleuf's Capricious Blessing",
        description: "+3 to a random BAGS attribute, re-rolled each run",
        stackable: false,
        modifiers: {
            custom: 3,
        },
    },
    // {
    //     id: 58,
    //     minLevel: 4,
    //     maxLevel: 5,
    //     name: "Black Pudding's Splash",
    //     description: "Melee: 25% damage to any other adjacent enemies when attacking",
    //     stackable: false,
    //     modifiers: {
    //         custom: 25,
    //     },
    // },
];
