export type Materials = "stone" | "ruins" | "temple" | "desert" | "volcanic";
export type Biomes =
    | "grasslands"
    | "forest"
    | "volcanic"
    | "frozen lands"
    | "mountains"
    | "graveyard"
    | "hells"
    | "desert";

export type TrapTypes = "pit" | "gas" | "web" | "spiked wall" | "lightning";
export type SpecialRooms =
    | "giant hive"
    | "the spider's web"
    | "ancient tomb"
    | "collector's trap"
    | "enchanted forest"
    | "temple of the gawds"
    | "torture chamber"
    | "rat warren"
    | "carrion lair"
    | "spiral maze"
    | "ye floor is lava"
    | "flooded chamber"
    | "witch's coven"
    | "king's vault";

export type Dwellers =
    | "skell"
    | "giant spider"
    | "hob gob"
    | "kobold"
    | "were rat"
    | "giant snake"
    | "wyrden cat"
    | "giant rat"
    | "zombie"
    | "bats"
    | "goblin"
    | "dwarv"
    | "slime"
    | "mirthcreant"
    | "giant wasp"
    | "collector"
    | "arkan"
    | "fey wing"
    | "gargoyle"
    | "crawler"
    | "dead knight"
    | "wisp"
    | "vodyanoi"
    | "ghast"
    | "ditch witch"
    | "paralisk"
    | "fomoian"
    | "brown pudding"
    | "devil bones"
    | "stachelig"
    | "shadow elf"
    | "brownie"
    | "jel cube"
    | "gains goblin"
    | "troll"
    | "cockatrice"
    | "traveler"
    | "bubble eyes"
    | "black pudding"
    | "harpy"
    | "quex"
    | "toothtube"
    | "night father"
    | "dramock"
    | "lost toad"
    | "lost punk"
    | "gem lizard"
    | "greiger"
    | "bananach"
    | "manticore";

export type GlitchTypes = "Rainbow" | "Inversion" | "Terminal: green" | "Retro lcd";

export type ItemTypes =
    | "coins"
    | "coinbag"
    | "key"
    | "chest"
    | "gem"
    | "food"
    | "light armor"
    | "sword"
    | "bow"
    | "dagger"
    | "scroll"
    | "potion"
    | "wand"
    | "helm"
    | "shield"
    | "axe"
    | "heavy armor"
    | "robes"
    | "necklace"
    | "ring"
    | "hat"
    | "boots"
    | "spear"
    | "hammer"
    | "wrist"
    | "shield"
    | "staff";
